name = "golddydev/lock-custom-token"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'golddydev/lock-custom-token'"

[repository]
user = "golddydev"
project = "lock-custom-token"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
